// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpos0KV3S2hRAkHhKzMaCrTUYG8r-s-i4',
    appId: '1:839822585943:web:bc53a2797261f9ccc3b312',
    messagingSenderId: '839822585943',
    projectId: 'auto-healthbot',
    authDomain: 'auto-healthbot.firebaseapp.com',
    databaseURL: 'https://auto-healthbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auto-healthbot.firebasestorage.app',
    measurementId: 'G-QT8Z7S2XE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1imjIDJmnSj1b6KQbee6HkiXYcGMm_gc',
    appId: '1:839822585943:android:37495748dbd1d4b8c3b312',
    messagingSenderId: '839822585943',
    projectId: 'auto-healthbot',
    databaseURL: 'https://auto-healthbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auto-healthbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4pmeIGS11AN_DB3qFMcyDhG49r5RwmI',
    appId: '1:839822585943:ios:b81a6dd8f8844070c3b312',
    messagingSenderId: '839822585943',
    projectId: 'auto-healthbot',
    databaseURL: 'https://auto-healthbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auto-healthbot.firebasestorage.app',
    iosBundleId: 'com.example.autoHealthbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb4pmeIGS11AN_DB3qFMcyDhG49r5RwmI',
    appId: '1:839822585943:ios:b81a6dd8f8844070c3b312',
    messagingSenderId: '839822585943',
    projectId: 'auto-healthbot',
    databaseURL: 'https://auto-healthbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auto-healthbot.firebasestorage.app',
    iosBundleId: 'com.example.autoHealthbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpos0KV3S2hRAkHhKzMaCrTUYG8r-s-i4',
    appId: '1:839822585943:web:fabb08eb906e32cbc3b312',
    messagingSenderId: '839822585943',
    projectId: 'auto-healthbot',
    authDomain: 'auto-healthbot.firebaseapp.com',
    databaseURL: 'https://auto-healthbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auto-healthbot.firebasestorage.app',
    measurementId: 'G-G8QQNCZEW8',
  );
}
